In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
hdb_df = pd.read_excel("resale17cc.xlsx")

hdb_df.head()

town  flat_type  floor_area_sqm  flat_model  lease_commence_date  \
0     8          2           104.0           5                 1989   
1     4          1            64.0          12                 1969   
2    13          4           141.0           1                 1989   
3    13          1            74.0           5                 1984   
4    12          2            95.0           9                 1982   

   resale_price  norm_resale_price Cluster  label  dlabel1  dlabel2  dlabel3  \
0      400000.0           0.403633     low      1        1        0        0   
1      404000.0           0.407669     low      1        1        0        0   
2      422000.0           0.425832     med      2        0        1        0   
3      375000.0           0.378406     low      1        1        0        0   
4      385000.0           0.388496     low      1        1        0        0   

   LH  
0   0  
1   0  
2   0  
3   0  
4   0

In [3]:
hdb_df.shape

(2000, 13)

In [4]:
type(hdb_df)

pandas.core.frame.DataFrame

In [13]:
x = hdb_df.iloc[:, 0:5].values
y = hdb_df.iloc[:, 8].values

print(x)

[[8.000e+00 2.000e+00 1.040e+02 5.000e+00 1.989e+03]
 [4.000e+00 1.000e+00 6.400e+01 1.200e+01 1.969e+03]
 [1.300e+01 4.000e+00 1.410e+02 1.000e+00 1.989e+03]
 ...
 [2.200e+01 2.000e+00 1.040e+02 5.000e+00 1.989e+03]
 [1.300e+01 2.000e+00 1.000e+02 5.000e+00 1.998e+03]
 [1.700e+01 2.000e+00 9.200e+01 1.000e+01 2.009e+03]]


In [31]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [32]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1600, 5)
(400, 5)
(1600,)
(400,)


In [33]:
from sklearn.preprocessing import StandardScaler
print(x_train)

scaler = StandardScaler()
print('\n',scaler.fit(x_train))
print('\n',scaler.mean_)

x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

print('\n',x_train)

[[8.000e+00 2.000e+00 1.040e+02 5.000e+00 1.989e+03]
 [1.000e+00 2.000e+00 9.100e+01 9.000e+00 1.978e+03]
 [7.000e+00 2.000e+00 9.500e+01 1.400e+01 2.011e+03]
 ...
 [0.000e+00 3.000e+00 1.190e+02 3.000e+00 1.980e+03]
 [1.500e+01 2.000e+00 8.200e+01 3.000e+00 1.975e+03]
 [1.300e+01 2.000e+00 1.030e+02 5.000e+00 1.985e+03]]

 StandardScaler()

 [  13.7125       2.13875     97.8203125    5.98875   1990.3725   ]

 [[-0.71873917 -0.1503189   0.25226699 -0.31528413 -0.12938186]
 [-1.59946987 -0.1503189  -0.27841857  0.9602016  -1.16632206]
 [-0.84455784 -0.1503189  -0.1151307   2.55455876  1.94449855]
 ...
 [-1.72528855  0.93306057  0.86459649 -0.95302699 -0.97778748]
 [ 0.16199154 -0.1503189  -0.64581626 -0.95302699 -1.44912394]
 [-0.0896458  -0.1503189   0.21144503 -0.31528413 -0.50645102]]


In [55]:
from sklearn.linear_model import LogisticRegression

hdb_class = LogisticRegression(random_state = 1, solver='newton-cholesky', penalty='l2')

hdb_class.fit(x_train, y_train)

hdb_test_class = hdb_class.predict(x_test)

In [56]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, hdb_test_class))

print('\n', classification_report(y_test, hdb_test_class))

[[132  45   0]
 [ 35 120   9]
 [  0  35  24]]

               precision    recall  f1-score   support

           1       0.79      0.75      0.77       177
           2       0.60      0.73      0.66       164
           3       0.73      0.41      0.52        59

    accuracy                           0.69       400
   macro avg       0.71      0.63      0.65       400
weighted avg       0.70      0.69      0.69       400



In [53]:
hdb_class1 = LogisticRegression(random_state = 1, solver='liblinear', penalty='l2', max_iter = 10)

hdb_class1.fit(x_train, y_train)

hdb_test_class1 = hdb_class1.predict(x_test)

In [47]:
print(confusion_matrix(y_test, hdb_test_class1))

print('\n', classification_report(y_test, hdb_test_class1))

[[132  45   0]
 [ 35 120   9]
 [  0  35  24]]

               precision    recall  f1-score   support

           1       0.79      0.75      0.77       177
           2       0.60      0.73      0.66       164
           3       0.73      0.41      0.52        59

    accuracy                           0.69       400
   macro avg       0.71      0.63      0.65       400
weighted avg       0.70      0.69      0.69       400

